### ISSUE TITLE
Raspberry Pi install Portainer

### ISSUE THREAD

**Issue by andymarden** [dtroncy/docker-rpi-dokuwiki#3]
I am trying to run this on a rpi 4m creating the container through Portainer (as I have all my other containers).

If I do a vanilla install, it works fine, but as soon as I try to map a volume with 'bind' it says that /pages cannot be accessed.

I assume I need to map the directories at /var/www/dokuwiki/* to directories on the host but it does not like tat - the container starts (with nothing in the logs) but then I get the /pages error when I try to access it.

What am I doing wrong here?

**Comment by dtroncy** [comment]
Hi @andymarden,

did you map /pages or /data/pages ?

**Comment by andymarden** [comment]
I think I tried both but I found another docker distribution that worked ok on the rpi now. Thanks for responding.

**Comment by dtroncy** [comment]
Ok, no problem
